name: Ubuntu CI

on: [pull_request]

jobs:
  test-fortress-galactic:

    runs-on: ubuntu-20.04
    container: 
      image: npslearninglab/watery_robots:galactic_current
    steps:
      - run: sudo chown -R `whoami`:`whoami` .
      - uses: actions/checkout@v2.4.0
        with:
            ref: gazebosim
            path: vrx

      - uses: actions/checkout@v2.4.0
        with:
            repository: ignitionrobotics/ros_ign
            ref: galactic 
            path: ros_ign
       
      - name: Set up workspace
        run: |
          mkdir -p /tmp/vrx_ws/src;
          ln -s `pwd` /tmp/vrx_ws/src;

      - name: Build and run tests
        shell: bash
        run: |
          cd /tmp/vrx_ws;
          source /opt/ros/galactic/setup.bash;
          IGNITION_VERSION=fortress colcon build --merge-install --executor sequential;
