name: Ubuntu CI

on: [pull_request]

jobs:
  test-fortress-galactic:

    runs-on: ubuntu-20.04
    container: 
      image: npslearninglab/watery_robots:galactic_current
    steps:
      - run: sudo chown -R `whoami`:`whoami` .
      - name: Checkout vrx
        uses: actions/checkout@v2.4.0
        with:
            ref: gazebosim
            path: vrx

      - name: Checkout Gazebosim 
        uses: actions/checkout@v2.4.0
        with:
            repository: ignitionrobotics/ros_ign
            ref: galactic 
            path: ros_ign
  
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@focal
        with:
          codecov-enabled: true
          doxygen-enabled: true
          cmake-args: '-DBUILD_TESTING=1'

